# Generated by Django 4.0.8 on 2023-09-13 09:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default=accounts.models.generate_default_user_id, max_length=12, unique=True),
        ),
    ]
