# Generated by Django 4.0.8 on 2023-09-10 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('abstract_link', models.URLField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('date_time', models.DateTimeField()),
                ('is_live', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_team_event', models.BooleanField(default=False)),
                ('registered_teams', models.ManyToManyField(blank=True, related_name='events_registered', to='events.team')),
                ('registered_users', models.ManyToManyField(blank=True, related_name='events_registered', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
